README.adoc
repositories.yaml
template/.github/workflows/daily_security.yml
template/.github/workflows/docker.yml
template/.github/workflows/publish_dev_artifacts.yml.j2
template/.github/workflows/publish_release_artifacts.yml.j2
template/.github/workflows/rust.yml
template/docker/Dockerfile.j2

Diff created by this PR:
```diff
diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
index 377b888..52f25e9 100644
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -92 +92 @@ jobs:
-        uses: actions-rs/clippy-check@v1
+        uses: actions-rs/clippy-check@v1.0.7
diff --git a/docker/Dockerfile b/docker/Dockerfile
index 404eee1..2e50888 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -16,0 +17 @@ COPY --from=builder /app/stackable-hbase-operator /
+COPY deploy/config-spec/properties.yaml /etc/stackable/hbase-operator/config-spec/properties.yaml
```
```diff
diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
index 377b888..52f25e9 100644
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -92 +92 @@ jobs: …
```

Add repository of the superset-operator

---

repositories.yaml

Addes Druid Operator to repositories under management

---

template/deploy/helm/[[product]]-operator/templates/roles.yaml.j2

https://stackable-workspace.slack.com/archives/C02FZ581UCD/p1640012955081400

Fix Zookeeper-operator RBAC rules

---

template/deploy/helm/[[product]]-operator/templates/roles.yaml.j2

Give OPA operator access to DaemonSets rather than StatefulSets

---

repositories.yaml
template/.dockerignore

Diagnosed and found together with @maltesander

Add .dockerignore to managed files and fix typo with retired files

---

repositories.yaml
template/.github/workflows/publish_main_artifacts.yml.j2
template/.github/workflows/publish_pr_artifacts.yml.j2
template/.github/workflows/publish_release_artifacts.yml.j2
template/Makefile.j2
template/deploy/helm/[[product]]-operator/Chart.yaml.j2

- I had a few outdated references to chart_testing.yaml in there
- I accidentally dropped the "description field" from the Chart which causes lint to fail

Fix my mistakes

---

template/deploy/helm/[[product]]-operator/templates/roles.yaml.j2

Fixes https://github.com/stackabletech/trino-operator/pull/97
/cc @sbernauer @soenkeliebau

Allow operators access to Secret objects

---

repositories.yaml

Added the airflow-operator to the templating scope.

Airflow templating

---

playbook/update_repo.yaml
renovate.json
template/.github/workflows/build.yml.j2
template/renovate.json
template/renovate.json.j2

1. Only run it during early mornings, GH bot notifications during the evening are really annoying
2. Centralize Actions PRs in operator-templating

Make Renovate slightly less annoying

---

template/.github/workflows/build.yml.j2
template/bors.toml

This allows us to specify this meta-job in bors as required and keeps the entire definition of which tests need to be run in the actual workflow file instead of having to update bors too for some changes.

Add a noop-job that symbolizes that all required tests have been successfully executed

---

template/python/cargo_version.py

Update Python formatting for cargo_version.py

---

template/scripts/generate-manifests.sh.j2

In #111 I accidentally hard coded the operator name as 'secret-operator' instead of using the {{ operator.name }} variable. This PR fixes this.

Replace hard coded value with variable

---

.github/workflows/reviewdog.yaml

Problem is described in https://github.com/reviewdog/reviewdog/issues/1158

Update action-yamlling and markdownlint

---

template/.github/workflows/reviewdog.yaml

This is the same change as #116 but in the files that are rolled out to downstream repos.

Update markdownlint and yamllint actions in template files

---

template/.github/workflows/build.yml.j2

Fixes #133 
Successfully tested with throw away repo:

Added prerelease_job used for selecting target Helm repo.

---

.github/workflows/run.yml

Fixes #178 
successful run: https://github.com/stackabletech/operator-templating/actions/runs/3013408792

Install protoc in GitHub workflow

---

template/.dockerignore
template/.gitignore.j2

Based on https://github.com/stackabletech/secret-operator/pull/181

Git-/dockerignore Nix image buffer

---

repositories.yaml
template/.github/workflows/build.yml.j2
template/rust-toolchain.toml.j2

See https://github.com/stackabletech/issues/issues/244

Pin rustc version

---

template/.readme/partials/borrowed/footer.md.j2.j2
template/.readme/partials/borrowed/links.md.j2.j2
template/.readme/partials/borrowed/overview_blurb.md.j2.j2

* add reusable overview paragraph
* some changes to existing partials

Small README-related addition

---

template/.github/ISSUE_TEMPLATE/config.yml.j2
template/.readme/partials/borrowed/documentation.md.j2.j2
template/.readme/partials/borrowed/links.md.j2.j2

Further tweaks might be included.

Add discussions link to README partial

---

template/.readme/partials/borrowed/footer.md.j2.j2

A small tweak, related to the new release.

Readme templating - bump the supported k8s version up

---

playbook/update_repo.yaml

This worked as seen here: https://github.com/stackabletech/operator-templating/actions/runs/3732418954

Added failed_when to Ansible tasks.

---

repositories.yaml

Bump rust version as preparation for the next release.

bump rust version to 1.65

---

template/Makefile.j2

change organization back to stackable

---

template/.github/workflows/build.yml.j2

Replaced temporary experimental helm repo with stable repo.

revert helm repo to stable

---

template/.github/workflows/build.yml.j2

This is a bit embarrasing...fourth time lucky...

Fix cargo install (really for real maybe)

---

template/.readme/partials/borrowed/links.md.j2.j2

Adds the discord signup link to the top link bar.

Add a link to the Discord server to all READMEs

---

repositories.yaml
template/.readme/partials/borrowed/footer.md.j2.j2

* Raise rust version to 1.68.2
* Clean-up remains of Ansible playbook for running kuttl tests
Part of https://github.com/stackabletech/issues/issues/333

Post release 23.4

---

repositories.yaml

DO NOT MERGE YET!
tested in zk here https://github.com/stackabletech/zookeeper-operator/pull/707

Post release bump rust from 1.68.2 to 1.71.0

---

.github/workflows/reviewdog.yaml
.github/workflows/run.yml
bors.toml
template/.github/pull_request_template.md
template/.github/workflows/build.yml.j2
template/.github/workflows/daily_security.yml
template/.github/workflows/reviewdog.yaml
template/.readme/partials/borrowed/footer.md.j2.j2
template/bors.toml

- Move from bors to merge queues
- Update GitHub actions dependencies
- Fix typo in readme
- Add spellcheck to reviewdog checks

Various updates for the 23.11 release

---

template/.github/ISSUE_TEMPLATE/normal-issue.md

Added a simple template with checklist for normal issues: this template also exists in the issues repo.

added a simple template with checklist for normal issues

---

template/.github/pull_request_template.md

All our products need to work in an entirely offline fashion and should not reference/hardcode any outside URLs etc.

Add an item to the checklist

---

template/.readme/partials/borrowed/footer.md.j2.j2
template/.readme/partials/borrowed/overview_blurb.md.j2.j2

Correct internal link, remove unnecassary www url part, adjusted product names.

Fix README

---

repositories.yaml

Part of https://github.com/stackabletech/issues/issues/407

chore: Bump Rust to 1.74.0

---

template/Tiltfile
template/deploy/helm/[[operator]]/templates/deployment.yaml.j2

Templating changes from https://github.com/stackabletech/opa-operator/pull/433#pullrequestreview-1696890759

Templating changes from the opa-operator user-info-fetcher work

---

playbook/playbook.yaml

This allow `./test.sh` to run the templating locally

fix: include templating step in the local test run

---

template/deploy/helm/[[operator]]/templates/_helpers.tpl
template/deploy/helm/[[operator]]/templates/deployment.yaml.j2

Part of https://github.com/stackabletech/issues/issues/501

feat(helm): support labels in values.yaml

---

config/rust.yaml

post release task: https://github.com/orgs/stackabletech/projects/16/views/1?pane=issue&itemId=48203304

chore: bump rust version

---

template/Makefile.j2

feat: add checks for 'nix' and Kubernetes cluster to 'run-dev' recipe in Makefile

---

template/.actionlint.yaml
template/.github/workflows/build.yml.j2

Adds ubicloud-standard-8-arm to operator build pipeline

Switching to ubicloud arm runner

---

template/.github/workflows/build.yml.j2

Successfully tested here: https://github.com/stackabletech/secret-operator/pull/462

version apt cache by architecture

---

config/rust.yaml

chore: Update Rust toolchain to 1.80.0

---

template/.github/workflows/build.yml.j2

Part of: https://github.com/stackabletech/issues/issues/631

chore(preflight): version 1.10.0

---

template/deploy/helm/[[operator]]/templates/deployment.yaml.j2

prerequisite for https://github.com/stackabletech/issues/issues/436#issuecomment-2413082601

Add KUBERNETES_SERVICE_DNS_DOMAIN to deployment templating

---

.pre-commit-config.yaml
template/.pre-commit-config.yaml.j2

Part of https://github.com/stackabletech/operator-templating/issues/450
Bumps actions in pre-commit workflow.

chore: Update pre-commit workflow

---

.github/ISSUE_TEMPLATE/pre-release.md
template/nix/sources.json

Part of https://github.com/stackabletech/issues/issues/647.
- Semi-regular `niv update`
- Fix the pre-release issue template tasklist
- 
> [!NOTE]
> This has been tested against secret-operator (both `make run-dev and `./scripts/run-tests`).

chore(template): Niv updates

---

template/.github/workflows/integration-test.yml

chore(ci): Set test parameters for scheduled runs

---

template/Makefile.j2

Part of https://github.com/stackabletech/issues/issues/611
```sh
make render-docs
```

chore(template): Add make render-docs

---

template/deny.toml

Part of https://github.com/stackabletech/issues/issues/677
Reasoning is given in the code comments

chore: Silence two Rust advisories

---

.github/workflows/generate_prs.yml
config/repositories.yaml
template/nix/README.md

- Drop edc-operator from templating
- Fix beku typo

chore: Drop edc-operator from templating

---

template/deny.toml

Part of https://github.com/stackabletech/issues/issues/677
> [!NOTE]
> I did consider leaving one excluding in, and commenting it so that we have a template for future exclusions. Let me know if you prefer that.

chore(template): Remove cargo deny exclusions

---

template/.pre-commit-config.yaml.j2

Fix typo in pre-commit config

---

template/nix/sources.json

Someone updated airflow so I thought it makes sense to make them all consistent again.

chore: Update nix/sources.json

---

template/.readme/partials/borrowed/footer.md.j2.j2

Add OpenSearch to the README file
The image `./template/.readme/static/borrowed/stackable_overview.png` will be updated in another pull request.

feat: Add OpenSearch to the README file
