stackabletech/operator-templating

template/.github/workflows/publish_main_artifacts.yml.j2
template/.github/workflows/publish_pr_artifacts.yml.j2
template/.github/workflows/publish_release_artifacts.yml.j2

The github actions files are missing the if statement to skip actions when PRs are created from a fork in a couple of places.
This causes CI runs to fail for example for [dependabot pull requests](https://github.com/stackabletech/superset-operator/runs/4432984859?check_suite_focus=true)

Added missing conditional line to skip building docker images if PR is created from a fork

---

template/.github/workflows/pr_generate_manifests.yml.j2
template/.github/workflows/rust.yml
template/bors.toml

These do not have access to the necessary secrets and will fail anyway.

Skip update manifest gh actions for pull requests that originate from forks

---

template/.github/workflows/rust.yml

This reverts commit 4162060d4df9108ed5830da0ef6aba2256884491.
Cargo-deny 0.11.0 no longer applies exceptions to workspace-local crates, causing CI failures everywhere.

Revert #130, downgrade cargo-deny-action to 1.2.6

---

template/docker/Dockerfile.j2

This is in order to protect against Log4Shell (CVE-2021-44228).

Added an environment variable to disable lookups in log4j strings.

---

.github/workflows/run.yml

Currently single quotes (`'`) in commit messages cause Ansible to go haywire, since that's the quotation character used in their basic variable format.
Rather than figure out how to escape quotes correctly for their format, this PR instead just uses `jq` to serialize it (with implied escaping) to JSON, and tells Ansible to load that.

Escape ansible variables properly

---

playbook/playbook.yaml
playbook/update_repo.yaml

Followup to #35. By setting `argv` to an explicit array with avoid running via a shell, and thus avoid the argument quotation problem.

Use Ansible command module rather than shell to fix commits with quotes (')

---

template/.github/workflows/rust.yml

These should be handled when doing the upgrade, and still cause false positives
in Post-2021 crates (such as zookeeper-operator).

Disable Rust 2021 compat warnings

---

template/.github/workflows/rust.yml

Tested in https://github.com/stackabletech/zookeeper-operator/tree/bugfix/ci-cache, compare https://github.com/stackabletech/zookeeper-operator/actions/runs/1667329561 to https://github.com/stackabletech/zookeeper-operator/actions/runs/1667310952.

Apply cache keys to each Rust job

---

template/deploy/helm/[[product]]-operator/templates/deployment.yaml

Required by https://github.com/stackabletech/kafka-operator/pull/275
Feels like this is the completely wrong place for this kind of thing, ideally we'd have some way for the repository to declare this kind of thing locally.. :/

Add reference to Kafka broker clusterrole

---

template/.github/pull_request_template.md
template/Makefile.j2

I kept forgetting this, but it is important. The operator deployed as a helm chart should work. At the moment this is also the easiest (only?) way to check if the RBAC rules work properly.
Also `make compile-chart` now always rebuilds the charts.

Updated PR Template to include a check of the helm chart

---

template/Makefile.j2

Some operators (looking at you, Regorule) do not have config-spec files, which caused the generate manifest step to fail after PR #61 which changed the syntax for copying these files.
This adds a check if any config-spec files are present and skips copying them if not. This requires that operators do not have .dummy files in place, as was the case for regorule (fixed in https://github.com/stackabletech/regorule-operator/pull/195 )

Make copying of config-spec conditional

---

repositories.yaml

After the rework of the hbase-operator the extra crates are not used anymore and were removed.
see stackabletech/hbase-operator#43

Remove unused extra crates for the hbase-operator

---

playbook/update_repo.yaml

Currently the playbook relies on ansibles "changed" state for actions, which may not be accurate, as we regenerate manifests after ansible is finished.
Added debug statement so we can tell in the output which operator is currently being processed.

Changes playbook to use 'git diff' to determine if a PR needs to be created

---

.yamllint.yaml
template/.github/workflows/build.yml.j2
template/.github/workflows/daily_security.yml
template/.github/workflows/reviewdog.yaml
template/.yamllint.yaml

This makes the changes Renovate tried to perform downstream in the repositories to pin action versions.
Added yamllint config to allow less whitespaces before inline comments to accomodate renovate.
Added comments to suppress detect-secret warnings.

Pin action versions

---

template/.github/workflows/build.yml.j2
template/.github/workflows/reviewdog.yaml

This bunches a couple of renovate action updates:
reviewdog/action-hadolint	        	minor	v1.6.0 -> v1.27.0
actions/github-script	                	major	v3 -> v5
reviewdog/action-markdownlint		minor	v0.1 -> v0.3
EmbarkStudios/cargo-deny-action		patch	v1.2.10 -> v1.2.11
actions/github-script	                	major	v3 -> v5
reviewdog/action-detect-secrets		pin	         v0.7.1 -> v0.7.1

Renovate Updates for Github Actions

---

template/Makefile.j2
template/renovate.json.j2

Adds a sort step to generatig the list of github action files to be ignored by renovate in the downstream repos.
fixes #74
Adds updating of timestamp on build.rs to makefile when generating crds.
fixes #75

Fix unneeded PRs and CRD generation error.

---

.github/workflows/reviewdog.yaml
.markdownlint.yaml

The action it's self was not tested but this works:
`docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest '**/*(*.md|*.md.j2)'`
where the output is:
```
template/deploy/DO_NOT_EDIT.md.j2:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "These Helm charts and manifest..."]
template/deploy/helm/[[product]]-operator/README.md.j2:21:77 MD034/no-bare-urls Bare URL used [Context: "https://docs.stackable.tech/"]
template/deploy/helm/[[product]]-operator/README.md.j2:23:65 MD034/no-bare-urls Bare URL used [Context: "https://github.com/stackablete..."]
template/deploy/helm/[[product]]-operator/README.md.j2:27:1 MD034/no-bare-urls Bare URL used [Context: "https://github.com/stackablete..."]
```

Added .markdownlint for self.

---

template/Makefile.j2
template/scripts/generate-manifests.sh.j2

This way it works with yq from snap.
On the other hand we now have a dependency on sponge. We can resolve it by moving around tmp files if we prefer

Fix to work with yq from snap

---

template/docker/Dockerfile.j2

In our Dockerfile(s) we use microdnf but do not use the command `microdnf clean all` at the end as recommended.
With the [release 2.9.1 of hadolint](https://github.com/hadolint/hadolint/releases/tag/v2.9.1), this is added as a check and reported. (after fixing issue https://github.com/hadolint/hadolint/issues/742)
This PR adds the cleanup as recommended.

Cleanup after install using microdnf

---

template/Makefile.j2

The current crds target in the Makefile only works for repositories which have a single binary crate.
This failed for the opa operator, as it has two binaries. To make matters worse, this wasn't noticed by make because the output of the cargo command is piped into another command, effectively hiding the error rc.
This PR fixes the crds target to directly specify the binary crate as well as adds an explicit SHELL to the Makefile with pipefail set.
```
opa-operator git:(main) ✗ make crds                                                                                                     <<<
mkdir -p deploy/helm/opa-operator/crds
cargo run crd | yq eval '.metadata.annotations["helm.sh/resource-policy"]="keep"' - > deploy/helm/opa-operator/crds/crds.yaml
error: `cargo run` could not determine …
```

Fix 'make crds' for repositories with multiple binary crates and improve error propagation in Makefile

---

playbook/update_repo.yaml

Check if a branch for the latest commit hash in the templating repo has already been created in downstream repos before attempting to push any changes.
fixes #102

Skip PR generation if branch for current source commit already exists in downstream repo

---

.github/workflows/reviewdog.yaml
template/.github/workflows/reviewdog.yaml

Theoretically we should be able to reduce them with the option detect_secrets_flags and --exclude-secrets
See https://github.com/reviewdog/action-detect-secrets and https://github.com/Yelp/detect-secrets
But this didn't work

Removed detect-secrets check as it produced many false positives

---

playbook/update_repo.yaml
repositories.yaml

This is required to avoid having templating revert https://github.com/stackabletech/secret-operator/pull/103. That PR is not suitable to roll out for all operators, since most operators should not need that level of privilege.

Ignore values.yaml for secret-operator

---

playbook/update_repo.yaml

We started running into failures when generating downstream PRs as the github runner started to run out of diskspace due to rust build artefacts accumulating.
This adds a `cargo clean` step at the end of each operator step to clean up state.

Add cargo clean step as the github runner started running out of disk space

---

template/tests/README-templating.md

While adding the capability to run the templated integration tests in Jenkins CI, I noticed that JQ is also a requirement for the tests to run.

JQ is a requirement for test scenario templating

---

rustfmt.toml

Merge this after https://github.com/stackabletech/secret-operator/pull/125 get's merged and didn't case any problems
I had a quick chat with @soenkeliebau and we agreed to give it a try

Add rustfmt.toml to configure formatter

---

template/tests/kuttl-test.yaml.jinja2

This reduces the default parallelism of kuttl from 8 to 2, as we have seen sporadic test failures due to test clusters running out of resources.
This value can be overridden by passing a parameter to the run_tests.sh script like follows: `run_tests.sh --parallel 4`
Most ci test defitions make use of this and for personal usage the value that may work here is heavily dependent on the size of the test cluster developers are using, so this will be customized a lot anyway.

Add default test parallelism to kuttl definition file.

---

template/deny.toml.j2

Allow Unicode-DFS-2016 license
[unicode-ident](https://crates.io/crates/unicode-ident) which is used by [serde](https://crates.io/crates/serde) added the Unicode-DFS-2016 license in version 1.0.2.

Allow Unicode-DFS-2016 license

---

template/scripts/docs_templating.sh

As this creates failing PRs in the downstream repos e.g. https://github.com/stackabletech/druid-operator/pull/283

Fix bash linter warnings from #163

---

template/.yamllint.yaml

Configure yamllint to accept non-indented sequences
`serde_yaml:0.9` does not indent sequences anymore, so yamllint should not complain about it.

Configure yamllint to accept non-indented sequences

---

template/Makefile.j2

This broke the build on NixOS, which _only_ provides /bin/sh and /usr/bin/env, and expects everything else to be found on the $PATH.

Don't assume that bash is at /bin/bash

---

template/.github/workflows/build.yml.j2

Install protoc in the GitHub workflows
The secret-operator depends on [`prost`](https://crates.io/crates/prost), a Protocol Buffers implementation for Rust. With version 0.11, `prost` will no longer provide a bundled `protoc`. Therefore `protoc` must be installed on the build runners.

Install protoc in the GitHub workflows

---

template/deny.toml

See https://stackable-workspace.slack.com/archives/C02FZ581UCD/p1664368256835939 for discussion.
This replaces the explicit allowlist with a generic ignore for all private crates, which should cut down on the spurious warnings (for operators that don't follow the "3-crate structure") and allow operator-specific utility crates to pass checks.
This will require the property `package.publish = false` to be set for each crate's `Cargo.toml` when merging the templating PRs. For example, for airflow-operator the following patch has to be applied:
```diff
diff --git a/rust/crd/Cargo.toml b/rust/crd/Cargo.toml
index 50a9ff9..4efdc59 100644
--- a/rust/crd/Cargo.toml
+++ b/rust/crd/Cargo.toml
@@ -6,6 +6,7 @@ license = "OSL-3.0"
name = "stackable-airflow-crd"
repository = …
```

Ignore license checks for all private crates

---

.github/workflows/run.yml

This has been causing CI failures the last few days since GH Actions now apparently includes a newer version in their image anyway. See https://github.com/stackabletech/operator-templating/actions/runs/3143897301/jobs/5109201435#step:4:19

Stop installing the GH CLI in CI

---

template/.readme/partials/borrowed/links.md.j2.j2

Turns out that a line with a comment gets removed during rendering, instead of leaving behind one _essential_ blank line.

Fix README badge regression

---

template/.readme/partials/borrowed/documentation.md.j2.j2
template/.readme/partials/borrowed/links.md.j2.j2

The operator doc paths differ from the repository names, and require a separate variable, set per operator.

Fix incorrect README docs links

---

template/.readme/partials/borrowed/links.md.j2.j2

The Jenkins jobs are no longer publicly viewable which also affected the visibility of the badges shown in the Operator READMEs. Jenkins allows the visibility being set to "only status" which requires to change the URL a little.
The badge no longer links to the Jenkins job as this would lead to a 404.

Integration Test Badge works with anonymous access to Jenkins.

---

template/.gitignore.j2
template/scripts/run_tests.sh
template/tests/README-templating.md
template/tests/ansible/playbook.yaml
template/tests/ansible/requirements.yaml

The expansion of the Kuttl templates is done by beku.py now. 
(see https://github.com/stackabletech/issues/issues/315 for details)

Migrated test expansion from Ansible to beku.py

---

template/scripts/run_tests.sh

Small improvement to usage of beku.py:
* cleanup of the old testsuite
* print out the beku.py version
(see https://github.com/stackabletech/issues/issues/315 for details)

Tests: cleanup workdir before creating testsuite.

---

template/.gitignore.j2
template/Tiltfile
template/default.nix

Currently we hardcode the registry to be used for pushing docker images to stackables sandbox registry.
While this is fine for Stackable members, it won't work for external contributors. This PR adds the ability to create a config file for Tilt in which different registries can be specified that will then be picked up.
Since this file should only be used for user specific settings, it is also added to the .gitignore file to avoid it accidentally ending up in vc.

Update Tiltfile to enable users overriding the default registry with custom values

---

template/.github/workflows/build.yml.j2
template/Tiltfile
template/default.nix
template/docker/Dockerfile.j2

This is required for https://github.com/stackabletech/secret-operator/pull/99. At some point we'd need to add extension hooks to let each operator decide some of these things, but... not yet.

Add Kerberos libraries to the Docker images

---

template/.pre-commit-config.yaml.j2

This adds Helm chart regeneration when committing new code. This ensures that the chart is always up-to-date.

chore: Add chart regeneration as pre-commit hook

---

template/Makefile.j2

The new target `stop-dev` was indented using spaces instead of tabs.

fix: Makefile indentation

---

template/tests/kuttl-test.yaml.jinja2

Set the timeout for KUTTL test suites to 120 seconds

Set the timeout for KUTTL test suites to 120 seconds

---

template/.github/workflows/build.yml.j2
template/Makefile.j2

Fixes https://github.com/stackabletech/issues/issues/381.
This PR integrates pushing our built artifacts (container images and Helm charts) to Harbor (and signing them). This is just for testing purposes, as Harbor is not really in use yet and the naming scheme of the artifacts location will likely change. The code in this PR pushes images to `oci.stackable.tech/stackable/images/` and Helm charts to `oci.stackable.tech/stackable/charts/`.
I generated the templating for airflow-operator and ran the build successfully:
https://github.com/stackabletech/airflow-operator/actions/runs/5784123312

Push artifacts to harbor

---

template/deny.toml

As discussed in Slack with Lars
Neded for `webpki-roots` and `option-ext`

Allow MPL-2.0 license

---

template/default.nix

Hoisted `csi-grpc` rules from listener-op, and removed the conditionals from #269.
This doesn't need to be rolled out immediately, the applicable repos have already been fixed.

Normalize nix build

---

template/nix/sources.json
template/nix/sources.nix

Upgrade nixpkgs in nix/sources.json to a revision with Rust 1.71.1
Our build pipeline uses Rust 1.71.1, so the same version should be used when building with Nix. The commit 676fe5e01b9a41fa14aaa48d87685677664104b1 is the one before Rust was upgraded to version 1.72.0.

Upgrade nixpkgs in nix/sources.json to a revision with Rust 1.71.1

---

template/default.nix
template/nix/sources.json

Previously we were running into https://github.com/briansmith/ring/issues/1786.
We need to update to pull in https://github.com/nix-community/crate2nix/pull/314.
Also, https://github.com/NixOS/nixpkgs/pull/266787 is not merged yet, so we set the env var to the expected value manually.
Once https://github.com/NixOS/nixpkgs/pull/266787 is merged, we should remove the manual env var.

Update crate2nix and set CARGO_MANIFEST_LINKS

---

template/default.nix
template/nix/sources.json

Follow-up of https://github.com/stackabletech/operator-templating/pull/289 as https://github.com/NixOS/nixpkgs/pull/266787 was merged

chore: Update nixpkgs and remove workaround

---

template/Tiltfile
template/deploy/helm/[[operator]]/templates/deployment.yaml.j2

This reverts commit 1876cb9f538dbe9de070da49082902c2010bd7c3.
It contained templating errors
- Tiltfile had templating, but was not a j2 file.
- The changes are no longer needed for opa-operator, and not yet needed by anything else.

Revert "Templating changes from the opa-operator user-info-fetcher work (#294)

---

template/.github/workflows/build.yml.j2
template/Makefile.j2

Needed for https://github.com/stackabletech/infrastructure/issues/138
Mainly:
Images are not stored in "stackable/images" anymore, but directly in "stackable".
Helm charts are not stored in "stackable/charts" anymore, but in "stackable-charts".
This removes slashes from the Harbor repository names and thus provides compatibility with other registries like Dockerhub and Quay.
Since Helm charts are stored in another Harbor project now ("stackable-charts"), a new Robot account for that project was needed ("robot$stackable-charts+github-action-build"). I decided not to create one Robot account with general permissions in Harbor, but instead single Robot accounts for each project (currently, one for "stackable" and one for "stackable-charts").
Also:
Capitalized the first letters of some …

New Harbor project names

---

template/Makefile.j2

Tiny fix: I just saw that, according to the CycloneDX 1.5 spec, the "url" attribute of "supplier" has to be an array instead of a string. Rest of the metadata is correct, I ran the SBOM through a validator.
I tested building the SBOM in this workflow: https://github.com/stackabletech/airflow-operator/actions/runs/7712824289
And validated it using https://github.com/CycloneDX/sbom-utility:
```
[INFO] Matching BOM schema (for validation): schema/cyclonedx/1.5/bom-1.5.schema.json
[INFO] Loading schema `schema/cyclonedx/1.5/bom-1.5.schema.json`...
[INFO] Schema `schema/cyclonedx/1.5/bom-1.5.schema.json` loaded.
[INFO] Validating `airflow-op-sbom.json`...
[INFO] BOM valid against JSON schema: `true`
```

Fix SBOM supplier metadata: "url" has to be an array of strings

---

template/.github/workflows/build.yml.j2

_This change was split from https://github.com/stackabletech/operator-templating/pull/311_.
Closes #310 
This will make it easier for operators to be updated independently with one change instead of over many lines.
Here is a test run against airflow-operator (I removed irrelevant diffs from previous changes not being applied to operators).
~~~patch
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index 81bf944..c72d0ed 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,6 +21,7 @@ env:
CARGO_TERM_COLOR: always
CARGO_INCREMENTAL: '0'
CARGO_PROFILE_DEV_DEBUG: '0'
+  RUST_TOOLCHAIN_VERSION: "1.74.0"
RUSTFLAGS: "-D warnings"
RUSTDOCFLAGS: "-D warnings"
RUST_LOG: "info"
@@ -44,7 +45,7 @@ jobs:
- uses: …

chore: templated ci environment variables instead of repeated version string (after render)

---

repositories.yaml
template/.github/workflows/build.yml.j2
template/nix/sources.json

Upgrade the default rust toolchain version to 1.75
Here is a test run against airflow-operator:
~~~patch
diff --git a/nix/sources.json b/nix/sources.json
index 92a5322..ca7ce78 100644
--- a/nix/sources.json
+++ b/nix/sources.json
@@ -17,10 +17,10 @@
"homepage": "",
"owner": "NixOS",
"repo": "nixpkgs",
-        "rev": "3f21a22b5aafefa1845dec6f4a378a8f53d8681c",
-        "sha256": "15y8k3hazg91kscbmn7dy6m0q6zvmhlvvhg97gcl5kw87y0svzxk",
+        "rev": "5ad9903c16126a7d949101687af0aa589b1d7d3d",
+        "sha256": "1i0nvgzzadbl29hzs5n4qbc0nnw69nh79b0kq3g7zi1926rczlqn",
"type": "tarball",
-        "url": "https://github.com/NixOS/nixpkgs/archive/3f21a22b5aafefa1845dec6f4a378a8f53d8681c.tar.gz",
+        "url": "https://github.com/NixOS/nixpkgs/archive/5ad9903c16126a7d949101687af0aa589b1d7d3d.t …

chore: Update default rust toolchain to 1.75

---

template/.github/workflows/build.yml.j2

Expressions (or at least the `env` context) is now allowed in `uses`.
This reverts commit edf2c5708809fdc9e1f889f12368ed9592a2d7b6. (#317)

revert: make it easier for individual operators to upgrade rust before templating

---

template/.github/workflows/build.yml.j2

This copies how we do it for stackable-cockpit. The previous attempt was reverted in #318 
- `uses` cannot contain expressions, or at least expressions using the `env` context.
- The action hash shouldn't need changing as often as the Rust version.

chore: Make it easier for individual operators to upgrade rust before templating

---

template/.github/workflows/build.yml.j2

I didn't notice the duplicate `with` keys introduced in #319

fix: duplicate `with` keys in build workflow

---

playbook/update_repo.yaml
template/.github/workflows/pr_reviewdog.yaml
template/Makefile.j2
template/Tiltfile
template/default.nix
template/shell.nix
template/shell.nix.j2

This is based on what I was doing in stackabletech/secret-operator#344, but to extend it out to all operators.
> [!IMPORTANT]
> Each operator will need to have `Cargo.nix` checked in to be able to make use of these changes. Otherwise they will get the following error when running `nix-shell`:
> ```
> error: getting status of '.../Cargo.nix': No such file or directory
> ```
>
> Run:
> ```sh
> make regenerate-nix
> git add Cargo.nix crate-hashes.json
> git commit -m "add crate2nix generated files"
>
> niv add stackabletech/beku.py
> git add nix/source.json
> git commit -m "add niv dependencies"
> ```
It includes some packages that are only needed for secret-operator:
- They are supposed to already be discovered/provided by default.nix, but I can't get it working.
- If we can't fix the above …

chore: Add shell.nix for all operators

---

.github/workflows/generate_prs.yml

This fixes the last PR #323 which errors with:
```
TASK [Operator [airflow-operator] regenerate crate2nix] ************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["make", "regenerate-nix"], "delta": "0:00:00.204998", "end": "2024-02-21 12:43:50.841070", "msg": "non-zero return code", "rc": 2, "start": "2024-02-21 12:43:50.636072", "stderr": "bash: line 1: nix: command not found\nmake: *** [Makefile:136: regenerate-nix] Error 127", "stderr_lines": ["bash: line 1: nix: command not found", "make: *** [Makefile:136: regenerate-nix] Error 127"], "stdout": "nix run -f . regenerateNixLockfiles", "stdout_lines": ["nix run -f . regenerateNixLockfiles"]}
```

ci: Add nix install action

---

.github/workflows/generate_prs.yml
template/default.nix

- add shebang to nix bash script (github actions runs `sh` by default, and we need `set -o pipefail`.
- add a dry-run workflow input so we can test things without raising a million PRs

fix: nix bash script

---

template/nix/sources.json

I had mistakenly done this change in each operator by hand (well, script), and not realised the sources were tracked here.

add niv dependencies

---

template/.github/workflows/build.yml.j2
template/Makefile.j2

- Remove the `build` target from the `publish` target in Makefile
- Do not run `make -e publish` if is is a PR from a fork (which has no access to secrets)
- Also don't run the openshift preflight checks which expects there to be an image to pull
---
Tested here:
- https://github.com/stackabletech/hbase-operator/pull/458
- https://github.com/stackabletech/hbase-operator/actions/runs/8078056432

ci(template): Fork awareness

---

template/.github/workflows/build.yml.j2

This fixes #334 which essentially broke push to `main` and tagging. It just happened to work for PRs.
This works as expected (though I can't test the merge to main/tag easily):

fix(template): fork detection that still works with tag/merge

---

template/.github/workflows/build.yml.j2
template/scripts/run_tests.sh

Install tests as needed by the operator test suite. 
This makes the operator installation the responsibility of the test suite.
Advantages:
* PR tests can now reference opreators from other PRs.
* Only install the operators that are needed for by the test suite.
* Running the integration tests from GH actions do not require workflows to know
about the operator installation.
Operator installation is optional and only done if a file named `tests/release.yaml` is found.
Here is an `release.yaml` example for the `trino-operator`
```yaml
---
releases:
tests:
releaseDate: 1970-01-01
description: Integration test
products:
commons:
operatorVersion: 0.0.0-dev
secret:
operatorVersion: 0.0.0-dev
listener:
operatorVersion: 0.0.0-dev
zookeeper:
operatorVersion: 0.0.0-dev
hdfs:
operatorVersion: …
```

feat(run_tests.sh): install operators as needed by the tests.

---

.github/workflows/generate_prs.yml
config/repositories.yaml
config/retired_files.yaml
config/rust.yaml
playbook/playbook.yaml

- **chore(gh): split repositories.yaml**
- **feat(gh): use matrix strategy to speed up downstream prs**

Parallelize downstream PRs

---

template/scripts/run-tests

Fix shebang of run-tests script
The `env` command is located in `/usr/bin` on most distros.

Fix shebang of run-tests script

---

template/.github/workflows/build.yml.j2

Adds a variable that selects the target architecture, as is done for docker-images https://github.com/stackabletech/docker-images/pull/626. N.B. preflight does not expect a `linux/` prefix but just `amd64` or `arm64`.
Fixes https://github.com/stackabletech/issues/issues/559.
Tested here:https://github.com/stackabletech/hive-operator/pull/450/files.
Dry-run for PRs: https://github.com/stackabletech/operator-templating/actions/runs/8881229144

chore: add arch for preflight

---

template/.github/workflows/build.yml.j2

- Remove duplicate checkout action
- Remove names from the checkout action step for consistency (earlier checkouts didn't have one)

fix: Remove duplicate checkout

---

template/nix/sources.json

- Use fixed beku version from stackabletech/beku.py#23
- Update crate2nix and nixpkgs

chore(nix): Update dependencies

---

template/.actionlint.yaml
template/.github/workflows/build.yml.j2
template/.gitignore.j2
template/Makefile.j2

This adds:
- build.yml.j2 updated workflow to use new cargo-build-action as well as leveraging BuildJet runner to natively support arm64
- Makefile.j2 Adding creation of manifest llists as well as sufficient tags for multi architecture releases of stackable operators

Multi-Architecture Operator pipeline

---

template/Makefile.j2

[NixOS does not ship these by default](https://github.com/coreutils/coreutils/blob/684db6cb9b06cbb4f246152da427da6f47aa16cc/build-aux/gen-lists-of-programs.sh#L12-L22) and arch is only a wrapper around `uname -m` anyway

chore: Use uname instead of arch in Makefile

---

template/deny.toml

Allow the Unicode-3.0 license
This license is required after upgrading the dependencies with `cargo update`.
Without this entry in deny.toml, `cargo deny check licenses` throws the following error:
```
error[rejected]: failed to satisfy license requirements                                                                                                                       10:05:25 [26/996]
┌─ registry+https://github.com/rust-lang/crates.io-index#zerovec-derive@0.10.2:4:12
│
4 │ license = "Unicode-3.0"
│            ^^^^^^^^^^^
│            │
│            license expression retrieved via Cargo.toml `license`
│            rejected: not explicitly allowed
│
= Unicode-3.0 - Unicode License v3:
=   - OSI approved
= zerovec-derive v0.10.2
└── zerovec v0.10.2
└── icu_collections v1.5.0
└── …
```

Allow the Unicode-3.0 license

---

template/tests/kuttl-test.yaml.jinja2

Increase the default timeout for integration test steps from 2 to 5 minutes
This timeout is also used for deleting namespaces. If a test succeeds but its namespace cannot be deleted in time, then the test still counts as failed.
```
logger.go:42: 11:54:15 | smoke_hbase-2.4.17_hdfs-3.3.6_zookeeper-3.8.4_listener-class-external-unstable_openshift-false/60-test-phoenix | [SUCCESS] Phoenix test was successful!
logger.go:42: 11:54:15 | smoke_hbase-2.4.17_hdfs-3.3.6_zookeeper-3.8.4_listener-class-external-unstable_openshift-false/60-test-phoenix | test step completed 60-test-phoenix
logger.go:42: 11:54:15 | smoke_hbase-2.4.17_hdfs-3.3.6_zookeeper-3.8.4_listener-class-external-unstable_openshift-false | skipping kubernetes event logging
logger.go:42: 11:54:16 | …
```

Increase the default timeout for integration test steps

---

template/.github/workflows/build.yml.j2

This PR adds the workflow_dispatch and schedule event triggers to run the operator image build manually if needed and to have a scheduled build once a week on the weekend.

feat: add workflow_dispatch and schedule event triggers to the operator build workflow

---

template/.github/PULL_REQUEST_TEMPLATE/pre-release-getting-started-script.md
template/.github/PULL_REQUEST_TEMPLATE/pre-release-rust-deps.md

Part of https://github.com/stackabletech/issues/pull/606

chore: Add getting-started scripts PR template

---

.flake8
.markdownlint.yaml
.pre-commit-config.yaml
.yamllint.yaml
config/retired_files.yaml
template/.flake8
template/.github/ISSUE_TEMPLATE/new_version.md.j2
template/.github/PULL_REQUEST_TEMPLATE/pre-release-getting-started-script.md
template/.github/PULL_REQUEST_TEMPLATE/pre-release-rust-deps.md
template/.github/workflows/build.yml.j2
template/.markdownlint.yaml
template/.pre-commit-config.yaml.j2
template/.readme/partials/borrowed/documentation.md.j2.j2
template/.readme/partials/borrowed/footer.md.j2.j2
template/.readme/partials/borrowed/header.md.j2.j2
template/.readme/partials/borrowed/links.md.j2.j2
template/.readme/partials/borrowed/overview_blurb.md.j2.j2
template/.readme/partials/borrowed/related_reading.md.j2.j2
template/deploy/DO_NOT_EDIT.md.j2
template/deploy/helm/[[operator]]/README.md.j2
template/scripts/ensure_one_trailing_newline.py
template/shell.nix

- Enable lints for jinja templates (markdown and yaml)
- Fix lints
- template: Ignore linting generated files
- template: Run udeps with `--all-targets`
- Replace flake8 with ruff

fix: Assorted lint and ci fixes

---

.pre-commit-config.yaml
template/.github/workflows/pr_pre-commit.yaml
template/.github/workflows/pr_reviewdog.yaml
template/.pre-commit-config.yaml.j2
template/scripts/run_tests.sh

- Remove flake8 from reviewdog checks (replaced by ruff in pre-commit checks below)
- Add pre-commit checks for PRs
- add shellcheck
- Resolve shellcheck warnings on script

chore: remove unused flake8 checks

---

template/.github/pull_request_template.md

Fixes typo in the link to the style guide in the PR template: .../docs-style-guide -> .../docs/style-guide

Fixes typo in the link to the style guide in the PR template

---

template/nix/sources.json

This will fix `make run-dev` for operators already using Rust 1.80 language features (such as druid) and unblock us from using them everywhere (e.g. in operator-rs)

chore: Bump to Rust 0.80.1 (finally)

---

.github/workflows/pr_pre-commit.yml
.pre-commit-config.yaml
config/rust.yaml
template/.github/workflows/pr_pre-commit.yaml.j2
template/.pre-commit-config.yaml.j2

Part of https://github.com/stackabletech/issues/issues/637
This fixes two things:
- Install the hadolint binary to be able to run the pre-commit hook
- Set the default language version of `node` to `system`. This fixes issues on NixOS systems.

fix(ci): Install hadolint in pre-commit workflow

---

renovate.json

`pre-commit` support is at the moment only in beta test for renovate so it has to be enabled manually in the config for renovate. I'll do that separately.
https://docs.renovatebot.com/modules/manager/pre-commit/

Configure renovate so that it should be able to pick up pre-commit

---

.github/ISSUE_TEMPLATE/pre-release.md
.github/workflows/pr_pre-commit.yml
.pre-commit-config.yaml
config/versions.yaml

This adds instructions to update dependencies related to the pre-commit workflows.
<details>
<summary>Issue Template Preview at 0158cbf</summary>
---
Part of <https://github.com/stackabletech/issues/TRACKING_ISSUE>
> [!NOTE]
> The pre-commit config and workflows need to be kept up-to-date to ensure
> usage of recent tooling versions. This requires some manual work in this
> repository.
```[tasklist]
```
> [!NOTE]
> During a Stackable release we need to ensure that every product operator uses
> the latest Rust toolchain (used by us). To keep the toolchain in sync across
> all our operators, we update the version centrally in this repository.
```[tasklist]
```
Replace the items in the task lists below with the applicable Pull Requests
```[tasklist]
```
</details>

chore: Add pre-commit instructions to issue template

---

.github/workflows/generate_prs.yml
playbook/group_vars/all/vars

Fixes:
```
GraphQL: Could not resolve to a User with the login of '@lfrancke'. (u000)
```

fix(generate_pr): Don't use @ mention for --review option in gh CLI

---

.pre-commit-config.yaml
template/docker/Dockerfile.j2

Ansible enables whitespace trimming for j2 template blocks, which means the `COPY` command was being hoisted into the comment on the line above.
The comment was only added so that hadolint would be able to parse the Dockerfile.
We've chosen to ignore j2 files rather than disable the trimming, as that could lead to other unknown problems across many files (with the least of the problems being new lint failures).
This does mean that formatting problems will only be picked up in PRs on the operators after templating, and fixes will need pulling back into operator-templating.

ci(pre-commit): Ignore j2 files for hadolint hook

---

template/.github/workflows/build.yml.j2
template/docker/Dockerfile.j2

This fixes an issue introduced by a past PR (https://github.com/stackabletech/operator-templating/pull/432). It uses an argument that doesn't exist ("STACKABLE_USER_NAME").
In the course of diagnosing that I stumbled across a few inconsistencies with our "docker-images" Dockerfiles which I am addressing here as well.
- Updates the Helm version used (not caught by Renovate yet)
- Sets a build timeout for the build & package phase to two hours (down from the default of 6)
- Adds the dnf.conf file
- Adds convenience utilities
- Adds a few common aliases and a better prompt

Fix broken Dockerfile and minor improvements

---

template/.github/workflows/pr_pre-commit.yaml.j2
template/.pre-commit-config.yaml.j2

- Revert 56f72e07fe1e17a64c514c4d4b97e66e957b0f00
- Install dependencies in the Github Actions Workflow

ci(pre-commit): Install dependencies needed for cargo test

---

.github/workflows/pr_pre-commit.yml
config/versions.yaml
template/.github/workflows/pr_pre-commit.yaml.j2

This PR updates all workflows to use the https://github.com/stackabletech/actions repo instead of local actions.

ci: Use stackabletech/actions repo

---

template/deploy/helm/[[operator]]/templates/deployment.yaml.j2

Not breaking, as this was added hours ago in https://github.com/stackabletech/operator-templating/pull/445, so no one actually uses it

Rename KUBERNETES_CLUSTER_DOMAIN to KUBERNETES_CLUSTER_DOMAIN

---

template/Makefile.j2

Same thing as https://github.com/stackabletech/actions/pull/11, but for our operator images. It probably makes sense for the same person to review both this PR and the other.
---
Use OCI type for PURLs, according to https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#oci
This is more correct in general and most importantly makes the PURL equal to the one Trivy generates for our container images.
Hint: To check the PURL Trivy generates, run for example these commands:
```
trivy image --scanners vuln -f cyclonedx -o airflow-result.cdx.json oci.stackable.tech/sdp/airflow-operator:0.0.0-dev-amd64
jq -r '.metadata.component.purl' airflow-result.cdx.json
```
---
The second commit includes the architecture in the component version in the SBOM (`0.0.0-dev-amd64` instead of …

fix: make PURLs use oci type / include architecture in `--source-version`

---

template/.github/workflows/build.yml.j2

Continuation of: https://github.com/stackabletech/operator-templating/pull/336

fix: Skip the build/publish manifest list job on forks

---

.github/workflows/generate_prs.yml
README.adoc
config/retired_files.yaml
playbook/playbook.yaml
playbook/update_repo.yaml
template/default.nix
test.sh

- Use correct filename, and add missing file to the retired files list.
- Refactor the playbook to run more steps in the local test.
- Pull in a change from stackabletech/opa-operator#622.

fix(playbook): Retired files and local testing improvements

---

template/.github/workflows/integration-test.yml
template/.github/workflows/pr_pre-commit.yaml.j2

Needs https://github.com/stackabletech/actions/pull/16 and requires pinning the action version.

ci: Add operator integration test workflow

---

template/Makefile.j2

Problem: SBOMs for our operator images do not contain cargo dependencies at the moment
We generate SBOMs for the Rust binaries at build time and Syft should pick them up to include the components in the SBOM for the container. This is done by the "SBOM cataloger" in Syft. Syft disabled the SBOM cataloger to run by default with [this PR](https://github.com/anchore/syft/pull/2527) (released with Syft v0.102.0). The Syft version regularly gets bumped by stackable-bot ([example](https://github.com/stackabletech/operator-templating/pull/427)), which indirectly disabled picking up the generated SBOMs in the container by bumping the Syft version.
This PR has two changes:
1. Pin CycloneDX version to 1.5 (was using the latest version by default, we can think about using 1.6 at some point, I …

fix: explicitly pick up SBOMs inside the container / specify CycloneDX version

---

template/.github/workflows/integration-test.yml

Disabled for now to allow merging the latest change (SBOM fix) with downstream PRs into the operator repos, will enable them after the release

chore: temporary disable integration tests

---

template/scripts/docs_templating.sh

The scripts was silently failing for people who don't have `jinja2`, and the error was hidden among a lot of bash debug output from the stackable-utils release scripts.

fix: Exit with error when jinja2 is not found

---

template/deny.toml

Came up in https://github.com/stackabletech/operator-rs/pull/907#discussion_r1848217771
```
error[rejected]: failed to satisfy license requirements
┌─ registry+https://github.com/rust-lang/crates.io-index#aws-lc-sys@0.22.0:4:44
│
4 │ license = "ISC AND (Apache-2.0 OR ISC) AND OpenSSL"
│            ────────────────────────────────━━━━━━━
│            │                               │
│            │                               rejected: license is not explicitly allowed
│            license expression retrieved via Cargo.toml `license`
│
├ OpenSSL - OpenSSL License:
├   - FSF Free/Libre
├ aws-lc-sys v0.22.0
└── aws-lc-rs v1.10.0
├── rustls v0.23.15
│   ├── hyper-rustls v0.27.3
│   │   └── kube-client v0.96.0
│   │       ├── kube v0.96.0
│   │       │   ├── stackable-certs v0.3.1
│   │ …
```

chore: Allow OpenSSL license (needed for ring and aws-lc-sys crates)

---

template/.github/workflows/integration-test.yml

Part of ~~and blocked by~~ https://github.com/stackabletech/actions/pull/21

ci: Add k3s and RKE2 test platforms to workflow inputs

---

config/versions.yaml

This bumps the Rust toolchain to 1.82.0.

chore: Bump Rust toolchain to 1.82.0

---

template/.github/workflows/build.yml.j2

See https://github.com/stackabletech/stackable-utils/pull/95/files
This PR:
- extends the tag regex to allow optional `-rcXX` suffixes
- suppresses the automatic setting of the version when merging a PR to a branch other than `main`. The version should be set in the PR creation (e.g. using stackable-utils): if this is not done then an error ocurs in the workflow e.g. `Cannot downgrade from 24.11.1-rc1 to 0.0.0-pr550`

ci: Workflow changes in preparation for release-candidates

---

template/.github/workflows/build.yml.j2

See stackabletech/stackable-utils#95 (files)
This PR:
- ensures that PRs against non-main (release) branches also incorporate the PR-number into the image name, so that images from a not-yet-merged release-candidate PR have a name distinct from the merged result
- e.g. `24.11.1-rc1-pr554` (unmerged PR branch) vs. `24.11.1-rc1` (merged and tagged in the rlease branch)

ci: set PR-suffix on PRs against non-main/release branches

---

template/.github/workflows/build.yml.j2

Fixes an error in the workflow condition to determine the base branch of a pull-request.
Tested:
- release-branch [PR](https://github.com/stackabletech/airflow-operator/pull/558) built [here](https://github.com/stackabletech/airflow-operator/actions/runs/12260962828/job/34206937064?pr=558)
- main-branch [PR](https://github.com/stackabletech/opa-operator/pull/666) built [here](https://github.com/stackabletech/opa-operator/actions/runs/12260179742/job/34204371351)

fix: PR base branch condition

---

template/Makefile.j2
template/Tiltfile
template/default.nix

- defaults (e.g. labels) are set to `oci.stackable.tech`
- objects are still pushed to Nexus and Harbor
- post 25.3, pushes to Nexus will be discontinued
- see [this](https://github.com/stackabletech/opa-operator/pull/671/commits/47ff0d19dc14623f289bf7a9e5d17ca0da9486b2) commit for necessary changes to remove Nexus actions

chore: set defaults to oci

---

.github/workflows/generate_prs.yml
.github/workflows/pr_pre-commit.yml
template/.github/workflows/build.yml.j2
template/.github/workflows/general_daily_security.yml
template/.github/workflows/integration-test.yml
template/.github/workflows/pr_pre-commit.yaml.j2

This bumps various actions which fail because of deprecated uses of actions/upload-artifact (v3).
Came up in https://github.com/stackabletech/airflow-operator/actions/runs/13054223406

ci: Bump broken actions

---

template/.pre-commit-config.yaml.j2
template/rustfmt.toml

Fixup of https://github.com/stackabletech/operator-templating/pull/136
Back in the day I put it in the wrong folder :man_facepalming: We already have this in secret-op for ~2 years now.
The amount of time I have seen suggestions regarding merging imports and sorting (std, external, crate), I'm very happy that we can solve all of that by automation :partying_face: 
`cargo +stable fmt` currently gives a warning, but still returns exit code 0 (so can be ignored)
Use `cargo fmt` to run the formatting.
See https://github.com/stackabletech/operator-templating/pull/136
> For what it's worth, you can run a single cargo command using the nightly toolchain by using `cargo +nightly fmt`.
>
> Rust-Analyzer should also allow you to set rustfmt-specific flags (for Emacs, put `(setq …

chore: Add rustfmt.toml with some unstable format options

---

template/deploy/helm/[[operator]]/templates/deployment.yaml.j2

Add the dynamic `checksum/config` annotation back in.
This is supposed to be used for rolling out the Deployment when the ConfigMap content changes.
Previously, this annotation only appeared when `.Values.podAnnotations` was set.
It was only discovered broken by adding podAnnotations and seeing that the `include` context was invalid, leading to this error:
```
Error: template: trino-operator/templates/deployment.yaml:20:28: executing "trino-operator/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: trino-operator/templates/configmap.yaml:4:10: executing "trino-operator/templates/configmap.yaml" at <.Files.Glob>: nil pointer evaluating interface {}.Glob
```
Note, this was always broken since inception in #7.

fix(template/helm): Add checksum/config annotation

---

config/versions.yaml
template/.github/workflows/pr_pre-commit.yaml.j2
template/.pre-commit-config.yaml.j2

This fixes the rustfmt pre-commit hook introduced in #477. Pre-commit tries to run `RUSTUP_TOOLCHAIN=nightly-2025-01-15` instead of `cargo fmt`, see [CI run](https://github.com/stackabletech/druid-operator/actions/runs/13131269765/job/36636760099#step:4:524).

fix(template/ci): Use local rustfmt hook

---

.github/ISSUE_TEMPLATE/pre-release.md
.github/workflows/generate_prs.yml
.github/workflows/pr_pre-commit.yml
.pre-commit-config.yaml
config/versions.yaml
template/.github/workflows/build.yml.j2
template/.github/workflows/general_daily_security.yml
template/.github/workflows/pr_pre-commit.yaml.j2
template/.pre-commit-config.yaml.j2

Part of <https://github.com/stackabletech/operator-templating/issues/484>
- Bumps local and templated workflow actions
- Hardens local and templated workflows
- Bumps local and templated pre-commit hooks
- Bumps the Rust toolchain to 1.84.1

chore: Pre-release updates for Stackable Release 25.3.0

---

template/.github/workflows/build.yml.j2

Part of <https://github.com/stackabletech/operator-templating/issues/484>
A new version of the cargo-deny-action was released because of the rustup 1.28 change of behaviour, see https://github.com/EmbarkStudios/cargo-deny-action/pull/92.
This change is already rolled out using the PRs from the previous rollout of #485.

template(ci): Bump cargo-deny-action to 2.0.7

---

template/.github/workflows/build.yml.j2

Currently, the rustfmt job uses the stable toolchain, which doesn't support various rustfmt options. This came up during the rollout of #495.

ci(template): Use nightly toolchain for rustfmt job

---

config/versions.yaml
template/.vscode/settings.json.j2
template/rustfmt.toml.j2

If the `rustfmt` command in `.vscode/settings.json` is overwritten, the edition needs to be provided explicitly as otherwise the command will fail and no formatting on save is performed.

chore(template): Template Rust edition in rustfmt config

---

template/deploy/helm/[[operator]]/templates/_telemetry.tpl
template/deploy/helm/[[operator]]/templates/deployment.yaml.j2

Part of https://github.com/stackabletech/issues/issues/639
Depends on
- https://github.com/stackabletech/operator-rs/pull/1009
- https://github.com/stackabletech/operator-rs/pull/1010
- https://github.com/stackabletech/operator-rs/pull/1012
This adds the `telemetry.envVars` Helm helper to create a list of environment variables passed on the `.telemetry` values.
**Example**
Given these values form the Helm `values.yaml` file
```yaml
telemetry:
consoleLog:
enabled: false
level: warn
format: json
fileLog:
enabled: true
level: debug
rotationPeriod: hourly
maxFiles: 6
otelLogExporter:
enabled: true
level: trace
endpoint: my-collector:4317
otelTraceExporter:
enabled: true
level: error
endpoint: my-collector:4317
```
the rendered env block in the Deployment looks like
```yaml
apiVersion: apps/v1 …
```

chore(template): Add Helm helper for telemetry env vars

---

template/deploy/helm/[[operator]]/templates/_telemetry.tpl

Part of https://github.com/stackabletech/issues/issues/639, follow-up of #501 
This improves the telemetry Helm helper to only emit env vars (e.g. for level) when the appropriate signal is enabled. This will no longer emit env vars even though the signal it self is disabled.

chore(template): Only emit env vars if telemetry signals are enabled

---

template/deploy/helm/[[operator]]/templates/_telemetry.tpl

This fixes the currently broken Helm files. Values of env vars need to be strings. The Helm deployment will otherwise fail with the following error:
```
Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number
into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```

fix(template): Quote fileLog.maxFiles env var in Helm helper

---

.github/workflows/generate_prs.yml

This adds the option to disable `strategy.fail-fast` if desired. This can help in situations where single jobs fail (e.g. due to upstream server errors), but other jobs get passed that error.
It is then possible to only re-run the failed jobs afterwards, instead of trying to run all of them together and having them succeed in one go.

ci(generate_prs): Add option to disable strategy.fail-fast

---

.github/workflows/generate_prs.yml

This is what we want in most situations, so set the default accordingly.

ci(generate_prs): Set fail-fast input default value to false

---

template/.pre-commit-config.yaml.j2

This PR:
- adds the `make regenerate-nix` command as a pre-commit hook to keep Nix files up to date.
- improves on which file changes the `regenerate-charts` hook runs.
- improves in which stages the local pre-commit hooks run.

chore(template): Add regenerate-nix to pre-commit config

---

.github/workflows/generate_prs.yml
.github/workflows/pr_pre-commit.yml
template/.github/workflows/build.yml.j2
template/.github/workflows/general_daily_security.yml
template/.github/workflows/pr_pre-commit.yaml.j2

This bumps various third-party actions, but also `stackabletech/actions/run-pre-commit` to make use of the recent improvements introduced in #503.
* rustsec/audit-check to 2.0.0
* sigstore/cosign-installer to 3.8.2
* azure/setup-helm to 4.3.0
* actions/setup-python to 5.6.0
* EmbarkStudios/cargo-deny-action to 2.0.11
* Swatinem/rust-cache to 2.7.8
* dtolnay/rust-toolchain
* stackabletech/actions/run-pre-commit to 0.8.0
* cachix/install-nix-action to 31.2.0

chore: Bump various actions to latest versions

---

.github/ISSUE_TEMPLATE/pre-release.md
.markdownlint.yaml
template/.github/PULL_REQUEST_TEMPLATE/pre-release-getting-started-script.md
template/.github/PULL_REQUEST_TEMPLATE/pre-release-rust-deps.md
template/.github/pull_request_template.md

byebye tasklists :sob:
Also moved `niv update` task into a template here. See: https://github.com/stackabletech/issues/pull/726

chore(issue_templates): Remove tasklists

---

template/deny.toml

Part of https://github.com/stackabletech/issues/issues/677
Fixup of #513
operator-rs is using the rsa crate, there is no fix yet

fix: Re-add RUSTSEC-2023-0071 exclusion

---

config/versions.yaml
template/.github/workflows/pr_pre-commit.yaml.j2

Came up in https://github.com/stackabletech/secret-operator/actions/runs/14877437184/job/41777443726.
Currently, the pre-commit workflow will fail, because Nix (the package manager) is not installed. This PR installs it in the latest version (2.28.3).

ci(template): Install Nix in pre-commit workflow

---

config/versions.yaml

The pinned nightly rustfmt disagrees with the current nightlies on some formatting decisions.. we might as well upgrade.

Bump nightly rust

---

.github/workflows/pr_pre-commit.yml
template/.github/workflows/build.yml.j2
template/.github/workflows/integration-test.yml
template/.github/workflows/pr_pre-commit.yaml.j2
template/.hadolint.yaml
template/.markdownlint.yaml
template/.pre-commit-config.yaml.j2
template/docker/Dockerfile.j2

The latest templating run caused pre-commit failures:
- hadolint complained about the Dockerfile which is why I added a SHELL statement and silenced the rest using a .hadolint.yaml file
- markdownlint complains about our PR template - it seems as if @NickLarsenNZ tried to fix this in April but changed the wrong markdownlint config file
While I was at it I updated various dependencies again...

update dependencies & add hadolint config & fix markdownlint

---

.github/workflows/generate_prs.yml
template/.pre-commit-config.yaml.j2

- Updates the install-nix-action (I forgot one place yesterday)
- Updates the comment for yamllint - the hash was updated already
- Avoids a message about a "legacy alias" from ruff: https://github.com/astral-sh/ruff-pre-commit/commit/39f54b73c72a16ee873859353d1ef40552a22e4d

feat: updates

---

template/default.nix

Part of https://github.com/stackabletech/issues/issues/732.
Mostly, this requires us to explicitly request that the contents of the Docker image be built on Linux. I also took the opportunity to split out `pkgs` to clarify when we build stuff for the local vs target environment.
This requires you to have a remote Nix builder available that runs on Linux. See https://github.com/stackabletech/nix-docker-builder for how to set that up.
Linux users should be unaffected, for us `pkgsLocal = pkgsTarget = old pkgs`.

Support the Tilt workflow on Darwin/macOS

---

template/default.nix

Primarily by disabling debug info.
For example, this slims down the airflow-operator image from 615MiB to 147MiB, and takes the incremental redeploy time from 57s to 29s (on my machine).
This improvement is a combination of the size of the debuginfo itself (~200MiB per binary), and not having to include build dependencies just because our debuginfo refers to them (primarily, this ended up pulling in GCC, which sits at ~260MiB just on its own).
The old behaviour (useful if you want to run it under a debugger.. though we probably want to support that separately somehow) can be restored by adding `--arg debuginfo 2` to the `nix-build` call.
In addition, this PR adds an option to remove the shell (and associated utililties) from the built images. This can be done by setting `--arg …

Slim down Nix builds

---

.github/workflows/generate_prs.yml
README.adoc
config/repositories.yaml
playbook/playbook.yaml
test.sh

Fixes #411.
config/repositories.yaml is now authoritative (once again) for the details of repository configuration (but generate_prs.yml must still contain the _names_ of all operators). Ansible now knows about the whole list of repositories and is responsible for filtering out the ones it cares about, rather than GitHub Actions generating a unique repository list for every shard. This means that Ansible is now able to generate proper indexes again.
Also refactors the github workflow a bit to avoid different code paths for dry and wet runs.

Restore repository indexing

---

template/docker/Dockerfile.j2

This makes it consistent with our product images which also have `findutils` installed.

Add findutils & STACKABLE_USER_NAME

---

.github/workflows/generate_prs.yml
.github/workflows/pr_pre-commit.yml
config/versions.yaml
template/.github/workflows/build.yml.j2
template/.github/workflows/integration-test.yml
template/nix/sources.json

Part of https://github.com/stackabletech/operator-templating/issues/512

chore: Bump Rust and action versions

---

.pre-commit-config.yaml
README.adoc
template/.pre-commit-config.yaml.j2

Part of https://github.com/stackabletech/operator-templating/issues/512

chore: Bump pre-commit hook versions

---

template/scripts/auto-retry-tests.py
template/scripts/run-tests

This script can be used to run the full test suite and then automatically retry the failing tests a configurable number of times. It can optionally keep the failed namespaces and it writes all the logs to files.
I did create this to run tests locally on my machine but I hope we can also make it usable for CI builds.
I am not the biggest fan of the output as it is very noisy but on the other hand I also don't want to miss crucial information during debugging.
This will generate output like this:
```
❯ python scripts/auto-retry-tests.py --parallel 4 --attempts-parallel 1 --attempts-serial 1 --venv venv --keep-failed-namespaces  --output-dir test-results
Starting Automated Test Suite with Retry Logic
==============================================
Step 1: Running initial full test suite... …
```

Add script to run and automatically retry tests

---

template/deploy/helm/[[operator]]/templates/deployment.yaml.j2
template/deploy/helm/[[operator]]/templates/service.yaml

Part of https://github.com/stackabletech/issues/issues/642
Needed for https://github.com/stackabletech/operator-rs/pull/1066
This PR only adds a Service on top of the operator Pod. This is needed, so that k8s can call the conversion webhook.
IMHO we can add this right now and start using it later.
This unblocks merging https://github.com/stackabletech/operator-rs/pull/1066, as that PR needs to `OPERATOR_NAMESPACE` and `OPERATOR_SERVICE_NAME` env vars

feat: Add Service on top of operators

---

.pre-commit-config.yaml
template/.github/workflows/build.yml.j2
template/.github/workflows/integration-test.yml
template/.pre-commit-config.yaml.j2

Came up in the rollout of #544 (and other recent changes), eg. in https://github.com/stackabletech/airflow-operator/pull/674.

chore: Enable strict mode for yamllint
